### ISSUE TITLE
Question regarding program used in screenshots

### ISSUE THREAD

**Issue by ob14** [torchgm/ActiveDesktopPlus#11]
What's the CPU and network utilisation deskband used in some of the screenshots?
![image](https://user-images.githubusercontent.com/75328666/111015070-eed5ea00-839e-11eb-8986-bf6fba5764a9.png)
I'm also curious about the custom tray icons.

**Comment by torchgm** [comment]
Oh, that'd be [XMeters](https://entropy6.com/xmeters/).
